L10n modification
speedcubingfrance/speedcubingfrance.org pull request #182
Opened 2022-03-18 12:36 UTC by SK927

Modified some localization keys in FR and EN.
Modified some pages content to make them localizable.
Updated layout of some previously localized pages.

2022-04-20 12:46 UTC, viroulep requested changes
Merci !

J'ai survolé le texte de la partie tuto, j'ai supposé que tu avais pas fait de gros changements.

2022-04-20 12:46 UTC, viroulep commented on app/views/votes/index.html.erb
> +        <td style="padding-right:1em"><%= link_to t("votes.layout.destroy"), vote, method: :delete, data: { confirm: I18n.t("votes.layout.are_you_sure") } %></td>
Il y a déjà une (plusieurs en fait :o) entrée pour ça, tu peux utiliser directement :
```suggestion
        <td style="padding-right:1em"><%= link_to t("votes.layout.destroy"), vote, method: :delete, data: { confirm: I18n.t("general.are_you_sure") } %></td>
```
(cette remarque s'applique aussi pour les autre utilisations du message :))

2022-04-20 12:46 UTC, viroulep commented on app/views/votes/new.html.erb
> +<h1><%= I18n.t("votes.layout.new") %></h1>
Question générale plutôt que sur cette occurrence particulière : pourquoi tu as utilisé `votes.layout.machin` plutôt que juste `votes.machin` ?

2022-04-20 12:46 UTC, viroulep commented on config/locales/fr.yml
> +      clear: "Effacer réponses"
```suggestion
      clear: "Effacer les réponses"
```

2022-04-20 12:46 UTC, viroulep commented on config/locales/fr.yml
> +      show: "Montrer"
```suggestion
      show: "Afficher"
```

2022-04-20 12:46 UTC, viroulep commented on config/locales/fr.yml
> +      destroy: "Détruire"
```suggestion
      destroy: "Supprimer"
```

2022-04-20 12:46 UTC, viroulep commented on config/locales/fr.yml
> +      p2_html: "Elle a pour but de promouvoir la discipline, notamment en facilitant l'organisation sur le territoire français de %{link_competitions} (régies par la World Cube Association). À ce tit
```suggestion
      p2_html: "Elle a pour but de promouvoir la discipline, notamment en facilitant l'organisation sur le territoire français de %{link_competitions} (régies par la World Cube Association). À ce titre, nous soutenons les organisateur·ice·s de différentes manières (prêt de matériel, aide au financement de salles, assurance, gestion des frais d'inscription, etc.). Nous intervenons également régulièrement dans le cadre de %{link_animations} (culturels, associatifs, caritatifs, commerciaux, médiatiques) en proposant démonstrations et initiations."
```

2022-04-20 12:46 UTC, viroulep commented on app/views/pages/speedcubing.html.erb
> +  <p><%= t("speedcubing.p3_html", link_wca: link_to(t("speedcubing.wca"), "https://www.worldcubeassociation.org/", {target: '_blank'}), link_comp: link_to(t("speedcubing.comp"), "https://www.worldcub
Je sais qu'on a pas de formateur automatique de code mais la ligne est suffisamment longue pour que ça devienne compliquer de bien la comprendre, je pourrais suggérer de la découper comme ça :
```suggestion
  <p>
    <%= t("speedcubing.p3_html",
          link_wca: link_to(t("speedcubing.wca"), "https://www.worldcubeassociation.org/", {target: '_blank'}),
          link_comp: link_to(t("speedcubing.comp"), "https://www.worldcubeassociation.org/competitions", {target: '_blank'})) %>
  </p>
```

(idem pour la ligne similaire plus loin dans le fichier)

2022-04-20 12:46 UTC, viroulep commented on app/views/posts/home.html.erb
> +      TEst
C'est un test pour vérifier que je suis ? :)

2022-04-20 12:46 UTC, viroulep commented on app/views/votes/_form.html.erb
> +		<%= I18n.t("votes.form.votes_already") %>
```suggestion
    <%= I18n.t("votes.form.votes_already") %>
```
(c'est un changement pas vraiment visuel mais ça remplace les tabs par des espaces)

2022-04-20 12:46 UTC, viroulep commented on config/locales/fr.yml
> +      list_5: "tands lors de salons du jeu..."
```suggestion
      list_5: "Stands lors de salons du jeu..."
```

2022-04-20 12:46 UTC, viroulep commented on config/locales/fr.yml
> +      p1_html: "Les Délégué·es français ont rassemblé l'ensemble des connaissances absolument indispensables à avoir pour envisager l'organisation d'une compétition dans %{link_document}. "
```suggestion
      p1_html: "Les Délégué·e·s français·e·s ont rassemblé l'ensemble des connaissances absolument indispensables à avoir pour envisager l'organisation d'une compétition dans %{link_document}. "
```

2022-04-21 12:53 UTC, SK927 commented on app/views/votes/new.html.erb
> +<h1><%= I18n.t("votes.layout.new") %></h1>
Je trouvais juste que c'était plus explicite sur le fait que le .new était un bouton de la page, plutôt que juste un texte remplacé. 
Dans l'absolu, j'aimerais reprendre à un moment tout le fichier pour l'assainir de toutes façons.

2022-08-13 10:03 UTC, viroulep requested changes
Merci pour les changements et désolé pour la latence de la relecture...

Tout à l'air presque bon pour merger, j'ai trouvé 2-3 typos qui restaient : après avoir fait les changements qui restent est-ce que tu pourrais tout squash dans un seul commit s'il te plait ?

2022-08-15 15:12 UTC, viroulep commented on app/views/votes/index.html.erb
> +      <th style="padding-right:1em"><%= I18n.t("votes.form.name") %></th>
C'est bô !

2022-08-15 15:13 UTC, viroulep approved these changes
LGTM!

2022-08-15 15:30 UTC, merged